name: random_winner_flutter
description: Random name generator draft system.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  soundpool: ^2.3.0
  screenshot: ^1.2.3
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/sfx/

  fonts:
    - family: PressStart
      fonts:
        - asset: assets/fonts/press_start_reg.ttf